### ISSUE TITLE
Is the JP Items (non Light) json no longer updated?

### ISSUE THREAD

**Issue by touchandswipe** [Deathmax/bravefrontier_data#17]
Just noticed the JP items (non light version) with recipes i believe is no longer updated. Is this intended? thx

**Comment by Deathmax** [comment]
I haven't had the time to update the data manually.

**Comment by touchandswipe** [comment]
No worries. Just thought it was automated. Thx

**Comment by touchandswipe** [comment]
I made this http://touchandswipe.github.io/bravefrontier/raidcompanion recently and it works well with English item recipes. if you're able to get recipes into the JP list, it would be doubly useful for JP server players too. :-) by the way how can one donate to you?

**Comment by Deathmax** [comment]
Sadly because of how recipe data is retrieved from the server, I can't automatically update JP's items.json without manually pulling data from my own device.

I don't have any method for donations atm.

**Comment by touchandswipe** [comment]
i see. that's a pity. is that something you can share on how to do it? or something i can help with perhaps on a regular basis (weekly) that i can pull what you require to get that going? I find that to be extremely useful for JP players and want to explore further on this. thank you
