### ISSUE TITLE
Errors in new EU content for some units

### ISSUE THREAD

**Issue by touchandswipe** [Deathmax/bravefrontier_data#21]
E.g. Unit 702 has a parsing error. Thought to let u know.

**Comment by Deathmax** [comment]
Why is there kanji in places where you only expect an int?

Will fix in the next push.

**Comment by touchandswipe** [comment]
Lol localization newbies in gumi. Thx

**Comment by touchandswipe** [comment]
thanks for the update on EU data. good stuff
