### ISSUE TITLE
Including Buff CODE ID for Leader skills?

### ISSUE THREAD

**Issue by touchandswipe** [Deathmax/bravefrontier_data#22]
The new EU content has units (e.g. Skalmold) with ATK buff for Females and ATK buff for 5+ Elementals. The ATK buff are showing up as being similarly named, and not tied to the conditions. Would you be able to name it in similar ways with other ATK type buffs in BB / SBB skills? thank you

**Comment by Deathmax** [comment]
The (id) convention was used for buffs, not passives.

I might use [id] instead for passives.

**Comment by touchandswipe** [comment]
Wouldn't [ ] have problems with json? Maybe just a - would do? E.g. ATK
Buff - 13 or ATK buff #17

**Comment by Deathmax** [comment]
AFAIK, [] doesn't need to be escaped. In any case, I'll be exposing the underlying ids for the effects in the next push.

**Comment by touchandswipe** [comment]
True that but [ ] is being read as an array type. Thanks  and would be nice
