### ISSUE TITLE
EU new units is not loaded somehow

### ISSUE THREAD

**Issue by touchandswipe** [Deathmax/bravefrontier_data#25]
Hi DeathMax,

I knew u did a refresh on the EU data. that said somehow the EU data are not loaded for the 3 new 5*s. Any thoughts on that?

**Comment by Deathmax** [comment]
EU may have changed where their files are located, so I might be fetching only the old files at the moment.

**Comment by touchandswipe** [comment]
thats a bummer. weird fellas
