### ISSUE TITLE
EU bugged and missing data for new 6* semi-goddesses

### ISSUE THREAD

**Issue by touchandswipe** [Deathmax/bravefrontier_data#28]
Hi Deathmax, there seems to be some bugged data in EU, that might impact on why not all the 6 semi-goddesses 6* data are available. would you be able to look into that?

**Comment by Deathmax** [comment]
Fixed in 0a589cd4af77a6f7f6051bf747e44d069463e561

**Comment by touchandswipe** [comment]
sweet :) ty
