### ISSUE TITLE
Sphere 武神刹刃『闘覇冥水』 has new type?

### ISSUE THREAD

**Issue by touchandswipe** [Deathmax/bravefrontier_data#30]
Seems this new sphere from RC6 crafting has a "null" in the sphere type text. Is it one of the new types introduced and would you need new values for it? thought to bring it to attention. Cheers

**Comment by DanUgore** [comment]
One of the new types introduced. It should come with a number, either 13 or 14.

**Comment by touchandswipe** [comment]
Fixed
