### ISSUE TITLE
EU update weekly

### ISSUE THREAD

**Issue by matxx** [Deathmax/bravefrontier_data#50]
Gumi EU has scheduled their update every friday (new rate ups on every friday). Could you set up a weekly update ?

**Comment by Deathmax** [comment]
Technically the bot doing the updates is already checking for updates every week, just that on EU the API url changes every so often, and I don't notice that it stopped receiving updates until someone brings it up.

**Comment by matxx** [comment]
well, I think there are "only" 2 CDNs for EU ("v1" and "v2"). I guess your bot is checking on "v2" since this last update took place on it. But these weekly update happened on "v1" last weeks. And yeah, that's confusing cause they aren't synced
