### ISSUE TITLE
Latest Pulls

### ISSUE THREAD

**Issue by Mich1997** [Deathmax/bravefrontier_data#52]
Due to Global having connection issues lately, is it affecting the bot? I think there should be a new pull for Global but nothing so far.

**Comment by touchandswipe** [comment]
which bot are u referring to ?

**Comment by Mich1997** [comment]
Global bot. Especially with Camilla batch out, having no updates from it is quite odd.

**Comment by Deathmax** [comment]
Bot wasn't updated for client version 1.7.2, it has since been updated and the scripts are currently running, push within 30 minutes.
